name: todos_api
description: The interface and models for an API providing access to todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  build_runner: ^2.10.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  meta: ^1.16.0
  uuid: ^4.5.1
